name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  charmcraft-build:
    name: Build Charm
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Read charmcraft version file
        id: charmcraft
        run: echo "channel=$(cat .charmcraft-channel)" >> $GITHUB_OUTPUT        
      - name: Install and prepare LXD snap environment
        run: |
          sudo apt-get remove -qy lxd lxd-client | true
          sudo snap list lxd | true
          sudo snap install lxd --channel=latest/stable
          sudo snap refresh lxd --channel=latest/stable
          sudo lxd waitready
          sudo lxd init --auto
          sudo chmod a+wr /var/snap/lxd/common/lxd/unix.socket
          sudo lxc network set lxdbr0 ipv6.address none
          sudo usermod -a -G lxd $USER
          sg lxd -c 'lxc version'
      - name: Remove Docker
        run: |
          # https://github.com/canonical/lxd-cloud/blob/f20a64a8af42485440dcbfd370faf14137d2f349/test/includes/lxd.sh#L13-L23
          sudo rm -rf /etc/docker
          sudo apt-get purge moby-buildx moby-engine moby-cli moby-compose moby-containerd moby-runc -y
          sudo iptables -P FORWARD ACCEPT
      - name: Install Charmcraft
        run: |
          sudo snap install charmcraft --classic --channel=${{ steps.charmcraft.outputs.channel }}
      - name: Build Charm
        run: |
          sg lxd -c 'charmcraft pack -v'
      - name: Upload charm artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./*.charm
      - name: Upload debug artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: charmcraft-logs
          path: /home/runner/snap/charmcraft/common/cache/charmcraft/log/charmcraft-*.log
